### PR TITLE
Add DNS over TLS, secure defaults

### PR DESCRIPTION
**Pull request by brianclemens**
- Added DNS over TLS support
- Use it by default
- Spelling corrections and removed a few trailing spaces

### CODE REVIEW

**Comment by brianclemens** [comment]
Not sure why the travis build is failing, I tried both the old `use-ssl-upstream` (works for me on Debian) and the newer `use-tls-upstream` (works for me on Arch).

**Comment by jdauphant** [comment]
@brianclemens Thanks for the contribution ;)
CI test over Ubuntu 14.04.5 LTS apparently, it's an old version of unbound.
I haven't see options to change that :thinking:

**Comment by jdauphant** [comment]
Same problem with 16.04

**Comment by jdauphant** [comment]
@brianclemens 
I have took a look at the unbound sources and "forward-tls-upstream" was introduce 1 year ago and "forward-ssl-upstream" 2 years ago, it's definetly not in ubuntu 14.04 or 16.04 (travis dont go further)

But there is the options "ssl-upstream" on "server" that was introduced 7 years ago : https://github.com/NLnetLabs/unbound/blame/68e4ef21dbb325c0b5479df63c7b3f0bc4a74d91/doc/example.conf.in#L643
But removed and replaced by "tls-upstream" 1 years ago

**Comment by jdauphant** [comment]
So the setup is different per Unbound version

**Comment by jdauphant** [comment]
@brianclemens "forward-tls-upstream" have been introduce 1 year ago in the code source of unbound. It will break compatibility with some distributions.
But you have introduce lot of nice modification, so I just have disable the default option and had comments

**Pull request merged**
